apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: getonboard
  labels:
    app: getonboard-backend
data:
  NODE_ENV: "development"
  PORT: "3001"
  DB_PORT: "5432"
  FRONTEND_URL: "https://getonboarducb.vercel.app/"

